Repository wecode-bootcamp-korea/fullstack1-1st-BaseNote-backend, pull requests merged in 2021-07, with the labels that each got.

#1 [박미정] prisma 모델링 완료
  prisma/migrations/20210708065224_create_model/migration.sql
  prisma/migrations/20210708065630_modify_product/migration.sql
  prisma/migrations/20210709062535_modify_password_varchar_length/migration.sql
  prisma/migrations/20210709071541_modify_mapping/migration.sql
  prisma/migrations/20210709080431_modified_to_camel_case/migration.sql
  prisma/migrations/20210709081506_add_cart_model/migration.sql
  prisma/migrations/20210709082604_add_mapping/migration.sql
  prisma/migrations/20210709084133_modified_cart_table/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: Status: Accepted

#3 [박미정] 프리즈마 모델링 수정
  prisma/migrations/20210710075143_add_series_number_in_product_model/migration.sql
  prisma/migrations/20210711021044_deleted_seasonal_table/migration.sql
  prisma/migrations/20210712020649_added_price_column_in_volume_model/migration.sql
  prisma/migrations/20210712020923_modified_wrong_spelling_in_cart_model/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#2 [감하영] 로그인 API 구현중
  .gitignore
  app.js
  controllers/UserController.js
  controllers/index.js
  models/UserDao.js
  models/index.js
  package-lock.json
  package.json
  prisma/migrations/20210712133654_change_volume_ml_type/migration.sql
  prisma/schema.prisma
  routes/UserRouter.js
  routes/index.js
  server.js
  services/UserService.js
  services/index.js
Labels: Status: Accepted

#5 [감하영] 액세스 토큰 인가 middleware 구현중
  app.js
  middlewares/validateToken.js
  models/UserDao.js
Labels: Status: 리뷰 요청

#6 [감하영] products_volume 테이블 & carts 테이블을 1대다로 수정
  prisma/migrations/20210714073249_add_cart_product_volume_id/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#8 [감하영] 장바구니 Read, Update API 구현
  controllers/OrderController.js
  controllers/index.js
  models/OrderDao.js
  models/index.js
  routes/OrderRouter.js
  routes/index.js
  services/OrderService.js
  services/index.js
Labels: Status: Accepted

#4 [박미정]회원가입 api 구현 중
  app.js
  controllers/UserController.js
  models/UserDao.js
  package-lock.json
  package.json
  routes/UserRouter.js
  routes/index.js
  server.js
  services/UserService.js
Labels: Status: 기능 구현 중, Status: 리뷰 요청

#9 [박미정] Products테이블의 series_number varchar로 수정
  prisma/migrations/20210715130517_modified/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#10 [감하영] 상품 리스트 API 구현중
  controllers/ProductController.js
  controllers/index.js
  models/ProductDao.js
  models/index.js
  routes/ProductRouter.js
  routes/index.js
  services/ProductService.js
  services/index.js
Labels: Status: Accepted, Status: 기능 구현 중

#13 [감하영] ProductKeyword model에 grade 컬럼 추가
  prisma/migrations/20210720144123_add_grade_in_product_keyword_model/migration.sql
  prisma/schema.prisma
Labels: Status: 리뷰 요청

#14 [감하영] 장바구니 Read API quantity 추가
  models/OrderDao.js
Labels: Status: 리뷰 요청

#16 [감하영] 토큰 만료, 유효하지 않은 토큰일 때 401 출력 및 에러 메시지 설정
  middlewares/validateToken.js
Labels: Status: Accepted

#17 [감하영] readme 작성
  README.md
Labels: Status: 리뷰 요청

#12 [박미정] 로그인 API에서 에러문구 추가
  controllers/UserController.js
  prisma/migrations/20210722095851_db/migration.sql
Labels: Status: 리뷰 요청
